import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import { copyFileSync, mkdirSync, writeFileSync, existsSync } from 'fs';
import path from 'path';
import * as sass from 'sass';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const distDir = 'dist';
const assetsDir = path.join(distDir, 'assets');
mkdirSync(assetsDir, { recursive: true });

/** Copy reveal.js CSS assets + manifest into dist/ */
function copyAssets() {
  const revealDist = path.join('node_modules', 'reveal.js', 'dist');
  for (const css of ['reveal.css', 'reset.css']) {
    // reveal.js 6.x ships these under dist/
    const src = existsSync(path.join(revealDist, css))
      ? path.join(revealDist, css)
      : path.join('node_modules', 'reveal.js', css);
    copyFileSync(src, path.join(assetsDir, css));
  }
  // highlight 插件主题 CSS
  const highlightDir = path.join(assetsDir, 'plugin', 'highlight');
  mkdirSync(highlightDir, { recursive: true });
  copyFileSync(
    path.join(revealDist, 'plugin', 'highlight', 'monokai.css'),
    path.join(highlightDir, 'monokai.css'),
  );
  copyFileSync('manifest.json', path.join(distDir, 'manifest.json'));
}

/** Compile plugin styles (SCSS) → dist/styles.css + dist/assets/reveal-plugin.css */
function compileStyles() {
  const result = sass.compile(path.join('src', 'styles', 'main.scss'), {
    style: prod ? 'compressed' : 'expanded',
  });
  writeFileSync(path.join(distDir, 'styles.css'), result.css);
  // 同一份样式也注入 iframe 内的 reveal 页面（grid/split/canvas/overrides）
  writeFileSync(path.join(assetsDir, 'reveal-plugin.css'), result.css);
}

const copyPlugin = {
  name: 'copy-assets',
  setup(build) {
    build.onEnd(() => {
      copyAssets();
      compileStyles();
    });
  },
};

const external = [
  'obsidian',
  'electron',
  '@codemirror/autocomplete',
  '@codemirror/collab',
  '@codemirror/commands',
  '@codemirror/language',
  '@codemirror/lint',
  '@codemirror/search',
  '@codemirror/state',
  '@codemirror/view',
  '@lezer/common',
  '@lezer/highlight',
  '@lezer/lr',
  ...builtins,
];

// 1) Obsidian plugin entry → dist/main.js (CJS, obsidian external)
const pluginContext = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external,
  format: 'cjs',
  target: 'es2018',
  loader: { '.html': 'text' },
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'dist/main.js',
  plugins: [copyPlugin],
});

// 2) reveal.js bundle for the preview iframe → dist/assets/reveal.bundle.mjs (ESM)
const revealContext = await esbuild.context({
  entryPoints: ['src/engine/reveal-bundle.ts'],
  bundle: true,
  format: 'esm',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: false,
  minify: prod,
  treeShaking: true,
  outfile: 'dist/assets/reveal.bundle.mjs',
});

if (prod) {
  await pluginContext.rebuild();
  await revealContext.rebuild();
  process.exit(0);
} else {
  await pluginContext.watch();
  await revealContext.watch();
}
