import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import { copyFileSync, mkdirSync, writeFileSync, existsSync, readFileSync } from 'fs';
import path from 'path';
import * as sass from 'sass';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// 构建标记：插件加载时打到控制台，用来确认 Obsidian 跑的到底是哪一次构建
// （改了文件不重载插件时，很难判断在跑新代码还是旧代码）
const buildStamp = new Date().toISOString().replace('T', ' ').slice(0, 19);

/*
 * mathjax-full 的 components/version.js 在没有 PACKAGE_VERSION 全局时，会用
 * `eval("require")` + `__dirname` 去读自己的 package.json 拿版本号 —— 浏览器里
 * 一执行就是 ReferenceError: require is not defined，整个 iframe bundle 起不来。
 * 构建期把版本号定义进去，那条分支就走不到了。
 */
const mathjaxVersion = JSON.parse(
  readFileSync(path.join('node_modules', 'mathjax-full', 'package.json'), 'utf8'),
).version;

const distDir = 'dist';
const assetsDir = path.join(distDir, 'assets');
mkdirSync(assetsDir, { recursive: true });

/** Copy reveal.js CSS assets + manifest into dist/ */
function copyAssets() {
  const revealDist = path.join('node_modules', 'reveal.js', 'dist');
  for (const css of ['reveal.css', 'reset.css']) {
    // reveal.js 6.x ships these under dist/
    const src = existsSync(path.join(revealDist, css))
      ? path.join(revealDist, css)
      : path.join('node_modules', 'reveal.js', css);
    copyFileSync(src, path.join(assetsDir, css));
  }
  // highlight 插件主题 CSS
  const highlightDir = path.join(assetsDir, 'plugin', 'highlight');
  mkdirSync(highlightDir, { recursive: true });
  copyFileSync(
    path.join(revealDist, 'plugin', 'highlight', 'monokai.css'),
    path.join(highlightDir, 'monokai.css'),
  );
  copyFileSync('manifest.json', path.join(distDir, 'manifest.json'));
}

/**
 * 把 iframe 需要的资源作为虚拟模块 `rfo:assets` 打进 main.js。
 *
 * Obsidian 的插件安装器（社区列表、BRAT）只下载 main.js / manifest.json / styles.css，
 * 不会带上任何额外目录。资源留在 dist/assets/ 里的话，用户装完是个渲染不出东西的空壳，
 * 只有手动解压 zip 才能用。故一律内联，代价是 main.js 变成 ~5 MB。
 */
function inlineAssetsPlugin() {
  const namespace = 'rfo-assets';
  return {
    name: 'inline-assets',
    setup(build) {
      build.onResolve({ filter: /^rfo:assets$/ }, () => ({ path: 'rfo:assets', namespace }));
      build.onLoad({ filter: /.*/, namespace }, () => {
        const read = (p) => readFileSync(path.join(assetsDir, p), 'utf8');
        const entries = {
          resetCss: read('reset.css'),
          revealCss: read('reveal.css'),
          highlightCss: read(path.join('plugin', 'highlight', 'monokai.css')),
          pluginCss: read('reveal-plugin.css'),
          bundleJs: read('reveal.bundle.mjs'),
        };
        const contents = Object.entries(entries)
          .map(([key, value]) => `export const ${key} = ${JSON.stringify(value)};`)
          .join('\n');
        return { contents, loader: 'js' };
      });
    },
  };
}

/** Compile plugin styles (SCSS) → dist/styles.css + dist/assets/reveal-plugin.css */
function compileStyles() {
  const result = sass.compile(path.join('src', 'styles', 'main.scss'), {
    style: prod ? 'compressed' : 'expanded',
  });
  writeFileSync(path.join(distDir, 'styles.css'), result.css);
  // 同一份样式也注入 iframe 内的 reveal 页面（grid/split/canvas/overrides）
  writeFileSync(path.join(assetsDir, 'reveal-plugin.css'), result.css);
}

const copyPlugin = {
  name: 'copy-assets',
  setup(build) {
    build.onEnd(() => {
      copyAssets();
      compileStyles();
    });
  },
};

// main.js 内联资源，必须先把这些资源准备好
copyAssets();
compileStyles();

const external = [
  'obsidian',
  'electron',
  '@codemirror/autocomplete',
  '@codemirror/collab',
  '@codemirror/commands',
  '@codemirror/language',
  '@codemirror/lint',
  '@codemirror/search',
  '@codemirror/state',
  '@codemirror/view',
  '@lezer/common',
  '@lezer/highlight',
  '@lezer/lr',
  ...builtins,
];

// 1) Obsidian plugin entry → dist/main.js (CJS, obsidian external)
const pluginContext = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external,
  format: 'cjs',
  target: 'es2018',
  define: { __BUILD_STAMP__: JSON.stringify(buildStamp) },
  loader: { '.html': 'text' },
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'dist/main.js',
  plugins: [copyPlugin, inlineAssetsPlugin()],
});

// 2) reveal.js bundle for the preview iframe → dist/assets/reveal.bundle.mjs (ESM)
const revealContext = await esbuild.context({
  entryPoints: ['src/engine/reveal-bundle.ts'],
  bundle: true,
  format: 'esm',
  target: 'es2020',
  define: { PACKAGE_VERSION: JSON.stringify(mathjaxVersion) },
  logLevel: 'info',
  sourcemap: false,
  minify: prod,
  treeShaking: true,
  outfile: 'dist/assets/reveal.bundle.mjs',
});

// reveal bundle 要先产出，main.js 的内联插件才读得到最新内容
if (prod) {
  await revealContext.rebuild();
  await pluginContext.rebuild();
  process.exit(0);
} else {
  await revealContext.rebuild();
  await pluginContext.watch();
  // 注意：watch 模式下改动 reveal-bundle.ts 需要重跑一次构建，
  // 内联进 main.js 的那份不会自动更新
  await revealContext.watch();
}
